### ISSUE TITLE
What is the difference of hierarchical and flat measurement

### ISSUE THREAD

**Issue by csorg** [Tencent/NeuralNLP-NeuralClassifier#10]

**Comment by liqunhit** [comment]
Are you referring to this? "Performance 3. Hierarchical vs Flat" in README.md?

**Comment by vikotse** [comment]
> Are you referring to this? "Performance 3. Hierarchical vs Flat" in README.md?

I think so.
And which dataset does "performance 3" used?

**Comment by coderbyr** [comment]
> > Are you referring to this? "Performance 3. Hierarchical vs Flat" in README.md?
> 
> I think so.
> And which dataset does "performance 3" used?

RCV1 dataset
