### ISSUE TITLE
how to handle unknow vocabulary on Tencent / NeuralNLP-NeuralClassifier

### ISSUE THREAD

**Issue by loveJasmine** [Tencent/NeuralNLP-NeuralClassifier#102]

**Comment by coderbyr** [comment]
vocabulary not in dict map will be mapped to `UNK`, refer https://github.com/Tencent/NeuralNLP-NeuralClassifier/blob/ecf291812c4235ed6ed01c5343b3b4e629eba2b7/dataset/dataset.py#L52
