### ISSUE TITLE
HMCN模型在Evaluation时报错

### ISSUE THREAD

**Issue by alisea47** [Tencent/NeuralNLP-NeuralClassifier#107]
您好！
首先非常感谢开源代码，但是我在做层次多标签分类时遇到了一些问题。
根据readme.md，我通过  `python train.py conf/train.hmcn.json`  语句进行训练，但通过 `python eval.py conf/train.hmcn.json` 语句进行评测时，报错信息如下：

Traceback (most recent call last):
  File "eval.py", line 113, in <module>
    eval(config)
  File "eval.py", line 75, in eval
    model = get_classification_model(model_name, empty_dataset, conf)
  File "eval.py", line 48, in get_classification_model
    model = globals()[model_name](dataset, conf)
KeyError: 'HMCN'

train.hmcn.json未进行更改，使用的是项目中提供的

非常感谢您的回复~

**Comment by MagiaSN** [comment]
感谢反馈，我们正在 #108 中修复这个bug
