### ISSUE TITLE
RCV1数据集

### ISSUE THREAD

**Issue by Rooooyy** [Tencent/NeuralNLP-NeuralClassifier#112]
您好！首先非常感谢各位开源的代码。目前我也在尝试用RCV1数据集做一些研究，但是官方提供的申请渠道已经403error，所以直接用了这个项目文件夹下的data/rcv1_xxx.json。后来发现rcv1_test.json里面测试数据量（7965条）和其他论文里写的 （[HiAGM](https://aclanthology.org/2020.acl-main.104/) [HGCLR](https://www.aclanthology.org/2022.acl-long.491.pdf)，781265条）对不上，train和dev对得上。请问项目里的数据是不是原版数据？如果不是的话能否麻烦提供一下原始数据，十分感谢！

**Comment by liqunhit** [comment]
项目里的test集是采样的，完整数据可以去官网下载。如有其他需求，欢迎邮箱联系。
