### ISSUE TITLE
HMCN模型的代码实现里面，没有Hierarchical Violation Penalty loss ?

### ISSUE THREAD

**Issue by littttttlebird** [Tencent/NeuralNLP-NeuralClassifier#113]
代码里HMCN（HMCN-F版本）的实现，只计算了global和local的交叉熵损失？

**Comment by MagiaSN** [comment]
目前没有实现，如果这个loss对你的任务有帮助，欢迎贡献代码，可以参考`model/loss.py`中`cal_recursive_regularize`的实现

**Comment by jamestang0219** [comment]
无进一步讨论，先close掉，有需要再重新open
