### ISSUE TITLE
请问这个层次分类支持bert吗？

### ISSUE THREAD

**Issue by cqcl1** [Tencent/NeuralNLP-NeuralClassifier#117]
请问这个层次分类支持bert吗？如果可以的话在哪里修改呢？

**Comment by jamestang0219** [comment]
> 请问这个层次分类支持bert吗？如果可以的话在哪里修改呢？

当时没有直接支持，不过model/layer.py中已经定义了multiheadattn，所以应该添加一些ffn层，不用进行较多的开发就可以定义一个bert，然后就可以使用bert进行层次分类了，欢迎提交mr
