### ISSUE TITLE
dataset RCV1 and yelp

### ISSUE THREAD

**Issue by paulpaul91** [Tencent/NeuralNLP-NeuralClassifier#13]

**Comment by paulpaul91** [comment]
1.RCV1 dataset, you provide the dataset, but statistics and data are not the same.
2.which year for the yelp dataset?

**Comment by coderbyr** [comment]
1、RCV1 has different versions. and here we use

**Comment by liqunhit** [comment]
1. The whole RCV1 dataset is not available for testing, so we just sample a part from original RCV1 as the example data for the quick-start running of NeuralClassifier.
2. 2019
