### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by JokerSeven** [Tencent/NeuralNLP-NeuralClassifier#16]
Thanks for your jobs!
I want to use this framework to handle multi-label classification task without hierarchical and I set "task_info.hierarchical"=false in conf/train.json. However, I have encountered this problem. Can you tell me how can I use this framwork without hierarchical?

**Comment by JokerSeven** [comment]
The dataset I used is RCV1, and I did not change other configurations in train.json except task_info.hierarchical.

**Comment by missrainbow91** [comment]
I guess you need to modify the file 'rcv1.taxonomy' in file folder 'data', the data in the file is hierarchical, you should change them into without hierarchy.

**Comment by coderbyr** [comment]
we have fix this problem, please refer the latest version.
