### ISSUE TITLE
Hierarchical can not work for the example

### ISSUE THREAD

**Issue by paulpaul91** [Tencent/NeuralNLP-NeuralClassifier#17]
can you provide a version for hierarchical classification? The example is just for muti-label without hierar. The hierar_taxonomy  is just for cal_recursive_regularize, which does not work for hierar.
Thanks

**Comment by missrainbow91** [comment]
I have run the code sucessfully, and the example is for multi-label with hierarchy, you can find the hierarchy in file "data\rcv1.taxonomy"

**Comment by coderbyr** [comment]
It should work if you follow our config, please detail more about your problem.

**Comment by paulpaul91** [comment]
> It should work if you follow our config, please detail more about your problem.

it works, but the hierarchy does not work, it is just for recursive_regularize, it can not recover the hierarchy relation.

**Comment by paulpaul91** [comment]
> I have run the code sucessfully, and the example is for multi-label with hierarchy, you can find the hierarchy in file "data\rcv1.taxonomy"
你给的样例数据集，根本就不符合层次，跟你们代码中要求的数据格式不是一个东西，rcv1.taxonomy这个只在cal_recursive_regularize中用到。好奇你们怎么发的ACL。。。。

**Comment by missrainbow91** [comment]
我不是腾讯的员工。。。我是自己运行出来了，并且用了自己的数据集可以进行预测

**Comment by missrainbow91** [comment]
> > I have run the code sucessfully, and the example is for multi-label with hierarchy, you can find the hierarchy in file "data\rcv1.taxonomy"
> > 你给的样例数据集，根本就不符合层次，跟你们代码中要求的数据格式不是一个东西，rcv1.taxonomy这个只在cal_recursive_regularize中用到。好奇你们怎么发的ACL。。。。

我不是腾讯的员工。。。我是自己运行出来了，并且用了自己的数据集可以进行预测
