### ISSUE TITLE
关于Multi-label text classification的疑问

### ISSUE THREAD

**Issue by qichaotang** [Tencent/NeuralNLP-NeuralClassifier#18]
请问对于 textcnn 而言，做  Binary-class text classifcation、Multi-class text classification、Multi-label text classification 这三个任务，实现区别有哪些不同？看了下代码，只看到 loss 和 evaluate 有点不一样

**Comment by liqunhit** [comment]
是的，你观察的是正确的。表示层（或者叫网络结构）是一致的。

**Comment by guotong1988** [comment]
同问
