### ISSUE TITLE
hierarchical taxonomy

### ISSUE THREAD

**Issue by liuLannister** [Tencent/NeuralNLP-NeuralClassifier#27]
你好，能否公开一下基于rcv1_train.json生成rcv1.taxonomy的代码？

**Comment by coderbyr** [comment]
> 你好，能否公开一下基于rcv1_train.json生成rcv1.taxonomy的代码？

RCV1 dataset provides a hierarchical taxonomy(ref: http://www.ai.mit.edu/projects/jmlr/papers/volume5/lewis04a/a02-orig-topics-hierarchy/rcv1.topics.hier.orig),  you can generate rcv1.taxonomy from origin Parent-Child format.
