### ISSUE TITLE
同样的数据集同样的模型每次跑出来的指标数据上下浮动1%左右

### ISSUE THREAD

**Issue by wilsonlsm006** [Tencent/NeuralNLP-NeuralClassifier#28]
你好，请问下我使用同样的算法，同样的数据集，每次跑出来的评价指标都不一样，比如精确率有时候是81%，有时候82%，有时候83%，浮动在2到3个点左右。

**Comment by liqunhit** [comment]
数据集使用的是NeuralClassifier自带的数据（rcv1）吗？
这个数据是从原始的rcv1数据集 sample一小部分的数据，量级很小，只是为了提供一个示例数据，有波动是有可能的。
