### ISSUE TITLE
IndexError: index 96 is out of bounds for axis 0 with size 96

### ISSUE THREAD

**Issue by SJIANAN** [Tencent/NeuralNLP-NeuralClassifier#31]
你好，我在自己的数据上跑时，总是显示题目中的错误：
File "/home/jsun/NeuralNLP-NeuralClassifier-master/evaluate/classification_evaluate.py", line 270, in evaluate
    if prob_np[predict_label_idx[j]] > threshold:
然后这是我的数据格式：
{"doc_label": ["label_06"], "doc_token": ["右", "侧", "甲", "状", "腺", "叶", "切", "除", "术"], "doc_keyword": [], "doc_topic": []}
在rcv1中跑却没错。

**Comment by lkluo** [comment]
@SJIANAN 找到解决方法了吗？

**Comment by SJIANAN** [comment]
找到了，top_k设置过大，原先代码设置是100，我的是96




            
            
                
                    
                            
                                
                            
                            
                                1760083838
                            
                    
                        
                            
                                    邮箱：1760083838@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 10/30/2019 00:13, lkluo wrote: @SJIANAN 找到解决方法了吗？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Tencent/NeuralNLP-NeuralClassifier/issues/31?email_source=notifications\u0026email_token=AHC6LY6FBMJA3QTNRBK3DXLQRBOLHA5CNFSM4JFLNBWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECRDZSA#issuecomment-547503304",
"url": "https://github.com/Tencent/NeuralNLP-NeuralClassifier/issues/31?email_source=notifications\u0026email_token=AHC6LY6FBMJA3QTNRBK3DXLQRBOLHA5CNFSM4JFLNBWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECRDZSA#issuecomment-547503304",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
