### ISSUE TITLE
请问.taxonomy文件怎么生成

### ISSUE THREAD

**Issue by YuMiaoTHU** [Tencent/NeuralNLP-NeuralClassifier#32]
你好，非常感谢你们的工作！我看到你们对于标签的表示是.taxonomy文件，请问这个文件是怎么生成的？谢谢

**Comment by coderbyr** [comment]
taxonomy文件中每一行表示的是parent node 和 child nodes之间的关系，是从原始类目体系中生成的；例如rcv1 的类目体系形如 （https://gist.github.com/gavinmh/6253739），从中可以提取每个父类目下所有的子类目
