### ISSUE TITLE
弱问multi-class分类和multi-label分类的区别？

### ISSUE THREAD

**Issue by guotong1988** [Tencent/NeuralNLP-NeuralClassifier#39]
谢谢谢谢

**Comment by coderbyr** [comment]
> 谢谢谢谢
multi-class: 多分类，区别于二分类，是指训练集中包含多个类目，如“教育”、“游戏”、“交通”等；
multi-label：多标签，区别于单标签，针对单个样本而言，是指一个样本包含多个标签；一般也是multi-class问题
