### ISSUE TITLE
How to use pre-trained embedding?

### ISSUE THREAD

**Issue by LxinG-YY** [Tencent/NeuralNLP-NeuralClassifier#40]
Can I use pre-trained embedding like word2vec or ELMO embedding in the embedding layer and how to apply?

**Comment by liqunhit** [comment]
For static embeddings, like word2vec, set the config item "token_pretrained_file" as file path of pretrained embedding.
For dynamic embeddings, like ELMO, due to its flexible use, it needs to be developed by users themselves.
