### ISSUE TITLE
Clarification around rcv1.taxonomy file 

### ISSUE THREAD

**Issue by tsu3010** [Tencent/NeuralNLP-NeuralClassifier#41]
Hi, Thanks for this really nice repository on text classification. Had a question regarding how the taxonomy file should be structured for any hierarchical classification problem (couldn't find anything on the readme regarding that). 

For an example problem where the possible hierarchies looks as follows
<img width="1119" alt="Screenshot 2020-01-09 at 11 14 29 AM" src="https://user-images.githubusercontent.com/10042752/72034923-5bec7c00-32d1-11ea-94c0-ff404020fc1a.png">

All-Science 
All-Science-NaturalScience
All-Science-NaturalScience-Biology
All-Humanities
All-Humanities-History
All-Humanities-History-WorldHistory
All-Vocabulary
All-Vocabulary-ReadingVocabulary

How should the taxonomy file be set up?

**Comment by coderbyr** [comment]
> Hi, Thanks for this really nice repository on text classification. Had a question regarding how the taxonomy file should be structured for any hierarchical classification problem (couldn't find anything on the readme regarding that).
> 
> For an example problem where the possible hierarchies looks as follows
> <img alt="Screenshot 2020-01-09 at 11 14 29 AM" width="1119" src="https://user-images.githubusercontent.com/10042752/72034923-5bec7c00-32d1-11ea-94c0-ff404020fc1a.png">
> 
> All-Science
> All-Science-NaturalScience
> All-Science-NaturalScience-Biology
> All-Humanities
> All-Humanities-History
> All-Humanities-History-WorldHistory
> All-Vocabulary
> All-Vocabulary-ReadingVocabulary
> 
> How should the taxonomy file be set up?

The taxonomy is used to calculate hierarchical loss,  which needs the parent-children relations. so, for the above example, the taxonomy should be like 
"ALL(suppose root node) \t  Science \t  Humanities \t Vocabulary  "
"Science \t NaturalScience" 
"NaturalScience \t Biology"
...

**Comment by odek53r** [comment]
> > Hi, Thanks for this really nice repository on text classification. Had a question regarding how the taxonomy file should be structured for any hierarchical classification problem (couldn't find anything on the readme regarding that).
> > For an example problem where the possible hierarchies looks as follows
> > <img alt="Screenshot 2020-01-09 at 11 14 29 AM" width="1119" src="https://user-images.githubusercontent.com/10042752/72034923-5bec7c00-32d1-11ea-94c0-ff404020fc1a.png">
> > All-Science
> > All-Science-NaturalScience
> > All-Science-NaturalScience-Biology
> > All-Humanities
> > All-Humanities-History
> > All-Humanities-History-WorldHistory
> > All-Vocabulary
> > All-Vocabulary-ReadingVocabulary
> > How should the taxonomy file be set up?
> 
> The taxonomy is used to calculate hierarchical loss, which needs the parent-children relations. so, for the above example, the taxonomy should be like
> "ALL(suppose root node) \t Science \t Humanities \t Vocabulary "
> "Science \t NaturalScience"
> "NaturalScience \t Biology"
> ...

Does the relations order affect the result?

**Comment by coderbyr** [comment]
> > > Hi, Thanks for this really nice repository on text classification. Had a question regarding how the taxonomy file should be structured for any hierarchical classification problem (couldn't find anything on the readme regarding that).
> > > For an example problem where the possible hierarchies looks as follows
> > > <img alt="Screenshot 2020-01-09 at 11 14 29 AM" width="1119" src="https://user-images.githubusercontent.com/10042752/72034923-5bec7c00-32d1-11ea-94c0-ff404020fc1a.png">
> > > All-Science
> > > All-Science-NaturalScience
> > > All-Science-NaturalScience-Biology
> > > All-Humanities
> > > All-Humanities-History
> > > All-Humanities-History-WorldHistory
> > > All-Vocabulary
> > > All-Vocabulary-ReadingVocabulary
> > > How should the taxonomy file be set up?
> > 
> > 
> > The taxonomy is used to calculate hierarchical loss, which needs the parent-children relations. so, for the above example, the taxonomy should be like
> > "ALL(suppose root node) \t Science \t Humanities \t Vocabulary "
> > "Science \t NaturalScience"
> > "NaturalScience \t Biology"
> > ...
> 
> Does the relations order affect the result?
what "order" means here? each line in the taxonomy file should keep the parent-child order, no matter the line order of "Science" and "NaturalScience" .
