### ISSUE TITLE
关于层次多标签分类算法的问题

### ISSUE THREAD

**Issue by egrcc** [Tencent/NeuralNLP-NeuralClassifier#43]
你好，

我最近也在做层次多标签的相关研究，我大概看了下代码，这里面使用的方法好像就是Large-Scale Hierarchical Text Classification with Recursively Regularized Deep Graph-CNN里的方法，不知道为什么在结果对比的时候会差这么多？
<img width="738" alt="截屏2020-02-27下午5 32 56" src="https://user-images.githubusercontent.com/6469953/75431068-41588a00-5987-11ea-837c-e6f98edde6d9.png">
具体是做了什么改进呢？
谢谢！

**Comment by liqunhit** [comment]
您好，这里除了层次分类的策略，还有各种text encoders的选择上，超参数也很重要。
