### ISSUE TITLE
What is hierarchical multi-label classification task?

### ISSUE THREAD

**Issue by Steffy-zxf** [Tencent/NeuralNLP-NeuralClassifier#5]
As refered, what is the difference between hierarchical multi-label classification task and multi-label classification task? Can you give a example?

**Comment by liqunhit** [comment]
The key difference is whether the classification taxonomy (or the label) is hierarchical.
For example, a hierarchical classification label: "sports--basketball", "sports" is level-1 label of hierarchical taxonomy. "basketball" is level-2 label, and it is a child of "sports". Those two labels has hierarchical relationship.

**Comment by CoSeCant-csc** [comment]
> The key difference is whether the classification taxonomy (or the label) is hierarchical.

Hi, thanks for your repo.  can u explain what is Hierarchical vs Flat measurement ? any reference is appreciated.
