### ISSUE TITLE
is_flat=False 评估时，是真的分高，还是评估的分高？

### ISSUE THREAD

**Issue by guotong1988** [Tencent/NeuralNLP-NeuralClassifier#51]
注意到，训练时还是flat的，
多谢！
@coderbyr @liqunhit

**Comment by coderbyr** [comment]
> 注意到，训练时还是flat的，
> 多谢！
> @coderbyr @liqunhit

这里训练和评估应该保持一致

**Comment by guotong1988** [comment]
哦，那是我看错了，训练时也有 非flat 的，我还没看到那
