### ISSUE TITLE
Hierarchical分类到底是怎么搞得？为什么Hierarchical评估时分高？

### ISSUE THREAD

**Issue by guotong1988** [Tencent/NeuralNLP-NeuralClassifier#52]
模型的输出还是class_num维，应该是loss那块是hierarchical优化，

**我以为是先分父类，再分子类，**

http://www.cs.cmu.edu/~sgopal1/papers/KDD13.pdf 总之是因为用了这个提升的？

@liqunhit @coderbyr 多谢！

**Comment by liqunhit** [comment]
是的，目前层次策略NeuralClassifier实现的是这个。但是提升并不是这一个变化带来的，因为NeuralClassifier还提供了非常多的文本分类encoder、优化算法等，所以加上层次分类策略之后，其他模块也跟着一起重新组合进行实验。
此外，更多业界最新的层次分类策略我们陆续在实现中，敬请期待。
