### ISSUE TITLE
请问下在multi-label分类时，如何处理一个文本没有标签的情况

### ISSUE THREAD

**Issue by karencceeee** [Tencent/NeuralNLP-NeuralClassifier#53]
如题

**Comment by coderbyr** [comment]
> 如题

是指预测阶段吗？

**Comment by karencceeee** [comment]
当数据集中，存在一些条目没有label，就会遇到下面的错误

NeuralNLP-NeuralClassifier-master\dataset\dataset.py", line 293, in _label_to_id
    assert label_id_list, "Label is empty: %s" % " ".join(sequence_labels)
AssertionError: Label is empty:

这个如何解决呢？我实验中的一些数据集（包括训练语料和测试语料，有无label的条目）

**Comment by coderbyr** [comment]
> 当数据集中，存在一些条目没有label，就会遇到下面的错误
> 
> NeuralNLP-NeuralClassifier-master\dataset\dataset.py", line 293, in _label_to_id
> assert label_id_list, "Label is empty: %s" % " ".join(sequence_labels)
> AssertionError: Label is empty:
> 
> 这个如何解决呢？我实验中的一些数据集（包括训练语料和测试语料，有无label的条目）

这种情况属于数据预处理部分，应该保证训练集和测试集的标签分布一致，没有标签的样本先过滤掉；
