### ISSUE TITLE
Different formula used for Macro F1

### ISSUE THREAD

**Issue by soumyac1999** [Tencent/NeuralNLP-NeuralClassifier#55]
The formula for macro F1 given in "Recursive Regularization for Large-scale Classification with Hierarchical and Graphical Dependencies" paper is
![image](https://user-images.githubusercontent.com/33203398/79069068-f7cebf00-7ce8-11ea-948d-d90d2a40fba5.png)

But your code uses
![image](https://user-images.githubusercontent.com/33203398/79069119-48461c80-7ce9-11ea-969b-0656bc2f1646.png)

Is there any reason for this?

**Comment by coderbyr** [comment]
> The formula for macro F1 given in "Recursive Regularization for Large-scale Classification with Hierarchical and Graphical Dependencies" paper is
> ![image](https://user-images.githubusercontent.com/33203398/79069068-f7cebf00-7ce8-11ea-948d-d90d2a40fba5.png)
> 
> But your code uses
> ![image](https://user-images.githubusercontent.com/33203398/79069119-48461c80-7ce9-11ea-969b-0656bc2f1646.png)
> 
> Is there any reason for this?
the latter is more common than the former, both are right when you choose the same one to compare performance of different methods.
