### ISSUE TITLE
同样的数据，label的这两种格式，得到的准召不一样，这是为什么啊

### ISSUE THREAD

**Issue by zouzoutingting** [Tencent/NeuralNLP-NeuralClassifier#59]
格式一：
"doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
格式二：
"doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]

其他配置都一样，用的是项目给的例子里默认的

**Comment by coderbyr** [comment]
> 格式一：
> "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> 格式二：
> "doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]
> 
> 其他配置都一样，用的是项目给的例子里默认的

格式一，样本只有两个标签；格式二，样本有五个标签；样本标签已经改变；

**Comment by zouzoutingting** [comment]
如果改成：
格式一：
"doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
格式二：
"doc_label": ["DeepLearning", "ComputationalNeuro"]

，准召一样吗

**Comment by zouzoutingting** [comment]
> > 格式一：
> > "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> > 格式二：
> > "doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]
> > 其他配置都一样，用的是项目给的例子里默认的
> 
> 格式一，样本只有两个标签；格式二，样本有五个标签；样本标签已经改变；

如果改成：
格式一：
"doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
格式二：
"doc_label": ["DeepLearning", "ComputationalNeuro"]

，准召一样吗

**Comment by coderbyr** [comment]
> > > 格式一：
> > > "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> > > 格式二：
> > > "doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]
> > > 其他配置都一样，用的是项目给的例子里默认的
> > 
> > 
> > 格式一，样本只有两个标签；格式二，样本有五个标签；样本标签已经改变；
> 
> 如果改成：
> 格式一：
> "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> 格式二：
> "doc_label": ["DeepLearning", "ComputationalNeuro"]
> 
> ，准召一样吗

不使用层级配置下，应该时相同的

**Comment by zouzoutingting** [comment]
> > > > 格式一：
> > > > "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> > > > 格式二：
> > > > "doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]
> > > > 其他配置都一样，用的是项目给的例子里默认的
> > > 
> > > 
> > > 格式一，样本只有两个标签；格式二，样本有五个标签；样本标签已经改变；
> > 
> > 
> > 如果改成：
> > 格式一：
> > "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> > 格式二：
> > "doc_label": ["DeepLearning", "ComputationalNeuro"]
> > ，准召一样吗
> 
> 不使用层级配置下，应该时相同的
是不是可以这样理解：
如果使用层级配置的话（样例里默认的配置），格式一是标准的格式。格式二，层级设置是失效的。

**Comment by XiangZhu0718** [comment]
> 格式一：
> "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> 格式二：
> "doc_label": ["DeepLearning", “MachineLearning”，“Computer”，"ComputationalNeuro"，“Neuro”]
> 
> 其他配置都一样，用的是项目给的例子里默认的

这个格式是训练数据准备的数据么，怎么经过转化得到train_json格式？
