### ISSUE TITLE
doc_label格式咨询

### ISSUE THREAD

**Issue by XiangZhu0718** [Tencent/NeuralNLP-NeuralClassifier#61]
你好，对于hierarchical+multi-label模型：
readme中：
"doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]

data/rcv1_train.json中："doc_label": ["E131", "E13", "E211", "E21", "ECAT"]
哪一种是训练hierarchical+multi-label模型正确的格式？
谢谢。

**Comment by guancheng817** [comment]
same quetion. have you solved that?

**Comment by guancheng817** [comment]
Same question? Have you solved that?

**Comment by coderbyr** [comment]
> 你好，对于hierarchical+multi-label模型：
> readme中：
> "doc_label": ["Computer--MachineLearning--DeepLearning", "Neuro--ComputationalNeuro"]
> 
> data/rcv1_train.json中："doc_label": ["E131", "E13", "E211", "E21", "ECAT"]
> 哪一种是训练hierarchical+multi-label模型正确的格式？
> 谢谢。

请参考：https://github.com/Tencent/NeuralNLP-NeuralClassifier/issues/58
