### ISSUE TITLE
doc_keyword和doc_topic的作用

### ISSUE THREAD

**Issue by unstory** [Tencent/NeuralNLP-NeuralClassifier#63]
训练数据里面的doc_keyword和doc_topic的作用是什么？代码没有完全看懂，是不是没有用到doc_keyword和doc_topic?

**Comment by coderbyr** [comment]
> 训练数据里面的doc_keyword和doc_topic的作用是什么？代码没有完全看懂，是不是没有用到doc_keyword和doc_topic?

这两部分为预留的用户可以自定义添加的 feature，目前还未完全实现

**Comment by MrRace** [comment]
@coderbyr  请问什么时候会更新自定义feature的功能？ 该 repo 似乎已经很久没有更新了。

**Comment by coderbyr** [comment]
目前customer feature支持fastext模型，后续会考虑支持自定义feature。
