### ISSUE TITLE
Bug in DatasetBase ？

### ISSUE THREAD

**Issue by JianxiangWang** [Tencent/NeuralNLP-NeuralClassifier#64]
![image](https://user-images.githubusercontent.com/9590519/82431867-d1f3c180-9ac1-11ea-87a5-72527c2ac0bb.png)
第82行函数的参数_mode, 在调用时没有用到，这是不是一个bug ？
还有105行，如果 self.config.data.generate_dict_using_json_files=True and self.config.data.generate_dict_using_all_json_files = True; 那么 _insert_vocab 会处理 训练数据 两次，这是合理的么 ？

**Comment by MemoriesJ** [comment]
Hi, I got the same question. 
我觉得你可以自己修改一下 
102 mode -> _mode
104 += -> =

**Comment by coderbyr** [comment]
> ![image](https://user-images.githubusercontent.com/9590519/82431867-d1f3c180-9ac1-11ea-87a5-72527c2ac0bb.png)
> 第82行函数的参数_mode, 在调用时没有用到，这是不是一个bug ？
> 还有105行，如果 self.config.data.generate_dict_using_json_files=True and self.config.data.generate_dict_using_all_json_files = True; 那么 _insert_vocab 会处理 训练数据 两次，这是合理的么 ？

conf中一般设置其中一个为true即可，这里的确可能出现上述情况，后面会fix下；
