### ISSUE TITLE
TextRCNN的实现是不是有问题

### ISSUE THREAD

**Issue by s1879281** [Tencent/NeuralNLP-NeuralClassifier#65]
textrcnn.py好像实现的仅仅是在CNN上叠加RNN，并不是说明里提到的RCNN (Lai et al., 2015)这篇论文里的模型？

**Comment by coderbyr** [comment]
> textrcnn.py好像实现的仅仅是在CNN上叠加RNN，并不是说明里提到的RCNN (Lai et al., 2015)这篇论文里的模型？

是的，实践中简单的CNN 和RNN的叠加效果会更好
