### ISSUE TITLE
how can i train a Hiearchical (multi-label) text classification (HMC) model

### ISSUE THREAD

**Issue by hujiajia0401** [Tencent/NeuralNLP-NeuralClassifier#74]
![image](https://user-images.githubusercontent.com/17944839/94243608-36300180-ff4a-11ea-933b-be1088c7bd4c.png)

**Comment by Cerebrock** [comment]
+1

**Comment by coderbyr** [comment]
Add some notes about how to train a model, please refer the [README](https://github.com/Tencent/NeuralNLP-NeuralClassifier#how-to-train-a-non-hierarchical-classifier)
