### ISSUE TITLE
请问下要怎么使用预先训练好的词向量？"initializer": "uniform"要改成啥，还有哪里要改额

### ISSUE THREAD

**Issue by Chenzongchao** [Tencent/NeuralNLP-NeuralClassifier#78]

**Comment by fan-nian** [comment]
请问你改了吗？想问一下具体是改哪里呢？

**Comment by coderbyr** [comment]
使用预训练的词向量，可以通过`feature.token_pretrained_file`来指定词向量文件的加载路径，各个参数的含义参见 [Configuration](https://github.com/Tencent/NeuralNLP-NeuralClassifier/blob/master/readme/Configuration.md)
