### ISSUE TITLE
"RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM" 

### ISSUE THREAD

**Issue by missrainbow91** [Tencent/NeuralNLP-NeuralClassifier#8]
The Error "RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM" occured, can u explain how to fix it?

**Comment by coderbyr** [comment]
please provide more details about your problem

**Comment by missrainbow91** [comment]
The error occured when I run the code "python train.py conf/train.json". At the first, I install the pytorch through "conda install pytorch", but the error "Torch not compiled with CUDA enabled" happened. So I use "conda install pytorch torchvision cudatoolkit=9.0 -c pytorch" to install pytorch with cuda, then the error "RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM" occured. I have try to solve it through many methods, but I failed. Hope you can solve my problem, thank you so much!

**Comment by missrainbow91** [comment]
I have solve the problems through uninstall pytorch and all the things I installed, and then install pytorch in "pytorch.org", and choose the version compitible with my system. So I guess the problem is because the pytorch I installed is not compitible with my system.

**Comment by coderbyr** [comment]
ok, keeps reminding us if you have any problem with NeuralClassifier
