### ISSUE TITLE
能否输出不同类别的概率

### ISSUE THREAD

**Issue by wingsyuan** [Tencent/NeuralNLP-NeuralClassifier#85]
请问，
这里面的所有的分类模块都能输出预测类别的概率吗？我的应用场景需要预测类别的概率值。。

**Comment by coderbyr** [comment]
可以，`predict.py`提供了对已训练完成的模型进行加载并进行预测的功能，`predict`函数输出的记为类别的预测概率，可以根据需要进行修改；
