### ISSUE TITLE
why the precision,recall, fscore always are same at each epoch?

### ISSUE THREAD

**Issue by loveJasmine** [Tencent/NeuralNLP-NeuralClassifier#93]

**Comment by kadirseker00** [comment]
https://stackoverflow.com/questions/54068401/can-the-precision-recall-and-f1-be-the-same-value

**Comment by loveJasmine** [comment]
I got it

**Comment by Ying091909** [comment]
> I got it

I met the same problem. Could you give me some clarification, thank you!
