### ISSUE TITLE
Any guide for generating taxonomy file？ (hierar_taxonomy: A text file describes taxonomy.)

### ISSUE THREAD

**Issue by david0718** [Tencent/NeuralNLP-NeuralClassifier#99]
Hi guys

Many thanks for such a good project. It is helpful for me.
Just want a case for "label_type": "multi_label", which is for labelling the knowledge.

I did not find any guide for this setting or how to generate a such a config file. I am a fresh man in such a field.
Really appreciated if you guys could provide any help?

Thanks
David

**Comment by coderbyr** [comment]
For `label_type: multi_label`, it means your model is multi-label classification, In your `dataset`, doc_label should be  a `list`, for example,  `doc_label": ["CCAT--C12", "GCAT--GCRIM", "GCAT--GPOL"]`
